// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace EnvelopeBySpine
{
    public class EnvelopeBySpineInputs: S3Args
    {
		/// <summary>
		/// Spine of the building envelope.
		/// </summary>
		[JsonProperty("Spine")]
		public Elements.Geometry.Polyline Spine {get;}

		/// <summary>
		/// Overall height of the building from grade.
		/// </summary>
		[JsonProperty("Building Height")]
		public double BuildingHeight {get;}

		/// <summary>
		/// Width of the mass perpendicular to the spine.
		/// </summary>
		[JsonProperty("Bar Width")]
		public double BarWidth {get;}

		/// <summary>
		/// Depth of the building envelope below grade.
		/// </summary>
		[JsonProperty("Foundation Depth")]
		public double FoundationDepth {get;}


        
        /// <summary>
        /// Construct a EnvelopeBySpineInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public EnvelopeBySpineInputs() : base()
        {
			this.Spine = new Elements.Geometry.Polyline(new []{new Vector3(0,0,0), new Vector3(0,1,0), new Vector3(1,1,0)});
			this.BuildingHeight = 100;
			this.BarWidth = 30;
			this.FoundationDepth = 20;

        }


        /// <summary>
        /// Construct a EnvelopeBySpineInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public EnvelopeBySpineInputs(Elements.Geometry.Polyline spine, double buildingheight, double barwidth, double foundationdepth, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.Spine = spine;
			this.BuildingHeight = buildingheight;
			this.BarWidth = barwidth;
			this.FoundationDepth = foundationdepth;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}